name: Test PowerShell Module (Windows)

# This workflow is disabled but ready for use
on:
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: 'Debug'

jobs:
  test-windows-ps5:
    name: 'Windows PowerShell 5.1'
    runs-on: [self-hosted, windows]
    strategy:
      matrix:
        dotnet-version: ['8.0.x', '9.0.x']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install PowerShell modules
        shell: powershell
        run: |
          Write-Host "PowerShell Version: $($PSVersionTable.PSVersion)"
          Install-Module -Name Pester -Repository PSGallery -Force -SkipPublisherCheck -AllowClobber
          Install-Module -Name PSWriteColor -Repository PSGallery -Force -SkipPublisherCheck -AllowClobber

      - name: Build .NET solution
        run: |
          dotnet restore TestimoX.sln
          dotnet build TestimoX.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Run PowerShell tests
        shell: powershell
        run: Write-Host 'No PowerShell tests defined'
        timeout-minutes: 30

  test-windows-ps7:
    name: 'Windows PowerShell 7'
    runs-on: [self-hosted, windows]
    strategy:
      matrix:
        dotnet-version: ['8.0.x', '9.0.x']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install PowerShell modules
        shell: pwsh
        run: |
          Write-Host "PowerShell Version: $($PSVersionTable.PSVersion)"
          Install-Module -Name Pester -Repository PSGallery -Force -SkipPublisherCheck -AllowClobber
          Install-Module -Name PSWriteColor -Repository PSGallery -Force -SkipPublisherCheck -AllowClobber

      - name: Build .NET solution
        run: |
          dotnet restore TestimoX.sln
          dotnet build TestimoX.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Run PowerShell tests
        shell: pwsh
        run: Write-Host 'No PowerShell tests defined'
        timeout-minutes: 30
