# .NET Testing Workflow
name: Test .NET

on:
  push:
    branches:
      - v1-legacy
      - v2-speedygonzales
    paths-ignore:
      - '*.md'
      - 'Docs/**'
      - 'Examples/**'
      - '.gitignore'
  pull_request:
    branches:
      - v1-legacy
      - v2-speedygonzales
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.x'
  BUILD_CONFIGURATION: 'Release'
  TEST_VERBOSITY: minimal # set to 'detailed' to restore full test output
  SUMMARIZE_FAILURES: true # set to 'false' to disable summarizing failing tests

jobs:
  test-windows:
    name: 'Windows'
    runs-on: windows-latest
    strategy:
      matrix:
        framework: [net8.0, net472]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup .NET Framework
        if: matrix.framework == 'net472'
        uses: microsoft/setup-msbuild@v2

      - name: Restore dependencies
        run: dotnet restore Sources/HtmlTinkerX.sln

      - name: Build solution
        run: dotnet build Sources/HtmlTinkerX.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Run tests for ${{ matrix.framework }}
        run: dotnet test Sources/HtmlTinkerX.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --framework ${{ matrix.framework }} --verbosity ${{ env.TEST_VERBOSITY }} --logger "console;verbosity=${{ env.TEST_VERBOSITY }}" --logger trx --collect:"XPlat Code Coverage"
        timeout-minutes: 10

      - name: Summarize failing tests
        if: failure() && env.SUMMARIZE_FAILURES == 'true'
        shell: pwsh
        run: |
          $trxFiles = Get-ChildItem -Recurse -Filter *.trx
          if ($trxFiles.Count -eq 0) {
            Write-Host "No TRX files found for failure analysis"
            exit 0
          }

          Write-Host "=== Failed Tests Summary ==="
          $failureCount = 0

          $trxFiles | ForEach-Object {
            try {
              Select-Xml -Path $_.FullName -XPath "//UnitTestResult[@outcome='Failed']" |
                ForEach-Object {
                  $name = $_.Node.testName
                  $msg = $_.Node.Output.ErrorInfo.Message ?? "No error message available"
                  Write-Host "❌ $name"
                  Write-Host "   $msg"
                  $failureCount++
                }
            } catch {
              Write-Host "Warning: Could not parse TRX file $($_.Name): $($_.Exception.Message)"
            }
          }

          if ($failureCount -eq 0) {
            Write-Host "No failed tests found in TRX files"
          } else {
            Write-Host "=== Total failed tests: $failureCount ==="
          }

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-windows-${{ matrix.framework }}
          path: '**/*.trx'

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports-windows-${{ matrix.framework }}
          path: '**/coverage.cobertura.xml'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: '**/coverage.cobertura.xml'

  test-ubuntu:
    name: 'Ubuntu'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore Sources/HtmlTinkerX.sln

      - name: Build solution
        run: dotnet build Sources/HtmlTinkerX.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Run tests
        run: dotnet test Sources/HtmlTinkerX.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --framework net8.0 --verbosity ${{ env.TEST_VERBOSITY }} --logger "console;verbosity=${{ env.TEST_VERBOSITY }}" --logger trx --collect:"XPlat Code Coverage"
        timeout-minutes: 10

      - name: Summarize failing tests
        if: failure() && env.SUMMARIZE_FAILURES == 'true'
        shell: pwsh
        run: |
          $trxFiles = Get-ChildItem -Recurse -Filter *.trx
          if ($trxFiles.Count -eq 0) {
            Write-Host "No TRX files found for failure analysis"
            exit 0
          }

          Write-Host "=== Failed Tests Summary ==="
          $failureCount = 0

          $trxFiles | ForEach-Object {
            try {
              Select-Xml -Path $_.FullName -XPath "//UnitTestResult[@outcome='Failed']" |
                ForEach-Object {
                  $name = $_.Node.testName
                  $msg = $_.Node.Output.ErrorInfo.Message ?? "No error message available"
                  Write-Host "❌ $name"
                  Write-Host "   $msg"
                  $failureCount++
                }
            } catch {
              Write-Host "Warning: Could not parse TRX file $($_.Name): $($_.Exception.Message)"
            }
          }

          if ($failureCount -eq 0) {
            Write-Host "No failed tests found in TRX files"
          } else {
            Write-Host "=== Total failed tests: $failureCount ==="
          }

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-ubuntu
          path: '**/*.trx'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: '**/coverage.cobertura.xml'

  test-macos:
    name: 'macOS'
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore Sources/HtmlTinkerX.sln

      - name: Build solution
        run: dotnet build Sources/HtmlTinkerX.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Run tests
        run: dotnet test Sources/HtmlTinkerX.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --framework net8.0 --verbosity ${{ env.TEST_VERBOSITY }} --logger "console;verbosity=${{ env.TEST_VERBOSITY }}" --logger trx --collect:"XPlat Code Coverage"
        timeout-minutes: 10

      - name: Summarize failing tests
        if: failure() && env.SUMMARIZE_FAILURES == 'true'
        shell: pwsh
        run: |
          $trxFiles = Get-ChildItem -Recurse -Filter *.trx
          if ($trxFiles.Count -eq 0) {
            Write-Host "No TRX files found for failure analysis"
            exit 0
          }

          Write-Host "=== Failed Tests Summary ==="
          $failureCount = 0

          $trxFiles | ForEach-Object {
            try {
              Select-Xml -Path $_.FullName -XPath "//UnitTestResult[@outcome='Failed']" |
                ForEach-Object {
                  $name = $_.Node.testName
                  $msg = $_.Node.Output.ErrorInfo.Message ?? "No error message available"
                  Write-Host "❌ $name"
                  Write-Host "   $msg"
                  $failureCount++
                }
            } catch {
              Write-Host "Warning: Could not parse TRX file $($_.Name): $($_.Exception.Message)"
            }
          }

          if ($failureCount -eq 0) {
            Write-Host "No failed tests found in TRX files"
          } else {
            Write-Host "=== Total failed tests: $failureCount ==="
          }

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-macos
          path: '**/*.trx'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: '**/coverage.cobertura.xml'
