name: Unified CI (PR + Claude Review)

on:
  pull_request:
    branches: ['**']
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**/*.md'
      - 'Docs/**'
      - '**/README.*'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.gif'
      - '**/*.svg'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE*'

jobs:
  ci:
    uses: EvotecIT/github-actions/.github/workflows/unified-ci.yml@main
    with:
      runs_on: '["ubuntu-latest"]'
      run_tests: true
      run_pester: false
      collect_coverage: true
      summarize_failures: true
      upload_artifacts: true
      claude_review: true
      # Leave empty to use default model, or set explicitly
      # claude_model: 'claude-3-5-sonnet'
      # Default sticky comments are enabled inside the reusable
      # claude_use_sticky_comment: true
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
