name: Unified CI (Multi-OS, simple)

on:
  pull_request:
    branches: ['**']
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**/*.md'
      - 'Docs/**'
      - '**/README.*'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.gif'
      - '**/*.svg'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE*'
  push:
    branches: ['main','master','release/**']
    paths-ignore:
      - '**/*.md'
      - 'Docs/**'
      - '**/README.*'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.gif'
      - '**/*.svg'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE*'

jobs:
  ci-windows:
    uses: EvotecIT/github-actions/.github/workflows/unified-ci.yml@main
    with:
      runs_on: '["windows-latest"]'
      run_tests: true
      run_pester: true
      collect_coverage: true
      summarize_failures: true
      upload_artifacts: true
    secrets: inherit

  ci-ubuntu:
    uses: EvotecIT/github-actions/.github/workflows/unified-ci.yml@main
    with:
      runs_on: '["ubuntu-latest"]'
      run_tests: true
      run_pester: false
      collect_coverage: true
      summarize_failures: true
      upload_artifacts: true
    secrets: inherit

  ci-macos:
    uses: EvotecIT/github-actions/.github/workflows/unified-ci.yml@main
    with:
      runs_on: '["macos-latest"]'
      run_tests: true
      run_pester: false
      collect_coverage: true
      summarize_failures: true
      upload_artifacts: true
    secrets: inherit
