name: Unified CI

on:
  pull_request:
    branches: ['**']
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**/*.md'
      - 'Docs/**'
      - '**/*.rst'
      - '**/*.adoc'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.gif'
      - '**/*.svg'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE*'
      - '**/README.*'
  push:
    branches: ['main','master','release/**']
    paths-ignore:
      - '**/*.md'
      - 'Docs/**'
      - '**/*.rst'
      - '**/*.adoc'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.gif'
      - '**/*.svg'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE*'
      - '**/README.*'

jobs:
  ci:
    uses: EvotecIT/github-actions/.github/workflows/unified-ci.yml@main
    with:
      run_tests: true
      collect_coverage: true
      rebuild_psd1: false
      run_pester: true
      summarize_failures: true
      upload_artifacts: true
      # Claude (optional, defaults visible for clarity):
      # claude_review: true
      # claude_model: ''
      # claude_use_sticky_comment: true  # default is true in reusable; keep commented for visibility
      # Optional:
      # solution: '**/*.sln'
      # build_configuration: 'Debug'
      # module_manifest: 'Module/MyModule.psd1'
      # ps_versions: '["5.1","7"]'
      # dotnet_versions: '["8.0.x"]'
      # runs_on: '["windows-latest"]'
      # enable_codecov: false
      # Post failing-tests summary as a comment (off by default):
      # post_summary_issue: true
      # post_summary_destination: 'issue'   # or 'pr' to post on the PR thread
      # sticky_summary_comment: true        # reuse the same comment if it exists
      # summary_comment_tag: 'evotec-ci-summary'  # hidden marker used to find the comment
      # summary_issue_title: 'CI Test Summary'
      # summary_issue_label: 'ci-summary'
    secrets: inherit
