name: Unified CI (Windows)

on:
  pull_request:
    branches: ['**']
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**/*.md'
      - 'Docs/**'
      - '**/README.*'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.gif'
      - '**/*.svg'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE*'
  push:
    branches: ['main','master','release/**']
    paths-ignore:
      - '**/*.md'
      - 'Docs/**'
      - '**/README.*'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.gif'
      - '**/*.svg'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE*'

jobs:
  ci:
    uses: EvotecIT/github-actions/.github/workflows/unified-ci.yml@main
    with:
      runs_on: '["windows-latest"]'
      run_tests: true
      run_pester: true
      collect_coverage: true
      summarize_failures: true
      upload_artifacts: true
      # module_manifest: 'Module/MyModule.psd1'    # required if rebuild_psd1 is true
      # rebuild_psd1: true                         # enable to refresh PSD1 via PSPublishModule
      # build_configuration: 'Debug'
      # frameworks: '["net8.0"]'
      # dotnet_versions: '["8.0.x"]'
      # claude_review: true
      # claude_model: ''
      # claude_use_sticky_comment: true
    secrets: inherit
